#!/bin/sh
# postinst script for cdemu-daemon
#

myerror ()
{
	echo "ERROR: $1" >&2
	exit 1
}

mywarning ()
{
	echo "WARNING: $1" >&2
}

case "$1" in
	configure)
		# Set permissions on cdemu daemon
		dpkg-statoverride --update --add root cdrom 755 "/usr/bin/cdemu-daemon" || myerror "Adding statoverride failed."
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#

exit 0

