#!/bin/sh
# prerm script for cdemu-daemon
#

myerror ()
{
	echo "ERROR: $1" >&2
	exit 1
}

mywarning ()
{
	echo "WARNING: $1" >&2
}

case "$1" in
	remove|upgrade|deconfigure)
		# Kill any session instances of cdemu-daemon running.
		pkill -KILL "^cdemu-daemon$" && mywarning "Killed running daemon instances."
	;;

	failed-upgrade)
	;;

	*)
		myerror "prerm called with unknown argument '$1'"
	;;
esac

#DEBHELPER#

exit 0
