#!/bin/sh
# prerm script for vhba-dkms
#

#DEBHELPER#

myerror ()
{
	echo "ERROR: $1" >&2
	exit 1
}

mywarning ()
{
	echo "WARNING: $1" >&2
}

case "$1" in
	remove|upgrade|deconfigure)
		# try to unload the module
		if test -d "/sys/module/vhba"; then
			modprobe -r "vhba" || myerror "Failed to unload module."
		else
			mywarning "Module was not running."
		fi
	;;

	failed-upgrade)
	;;

	*)
		myerror "prerm called with unknown argument '$1'."
	;;
esac

exit 0

